// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aqaurius6666/goserverless/internal/repository/dynamodb"
	"github.com/aqaurius6666/goserverless/internal/usecase"
)

// Injectors from wire.go:

func BuildDeps(opts LambdaOpts) (LambdaDeps, error) {
	ddbTable := opts.DdbTableName
	client, err := dynamodb.NewDynamodbClient()
	if err != nil {
		return LambdaDeps{}, err
	}
	ddbUserRepository := &dynamodb.DdbUserRepository{
		TableName: ddbTable,
		Client:    client,
	}
	userUseCaseImpl := &usecase.UserUseCaseImpl{
		UserRepo: ddbUserRepository,
	}
	lambdaDeps := LambdaDeps{
		UserUseCase: userUseCaseImpl,
	}
	return lambdaDeps, nil
}

// wire.go:

type LambdaDeps struct {
	UserUseCase usecase.UserUseCase
}

type LambdaOpts struct {
	DdbTableName dynamodb.DdbTable
}
